class Constants:
    COMMAND_ACKNOWLEDGED_BY_SURIEL = "✅"
    TIME_LIMIT_LOOP_INTERVAL_MINUTES = 1
    DESIGN_TIME_LIMIT_MINUTES = 60
    CODE_TIME_LIMIT_MINUTES = 20
    REVIEW_TIME_LIMIT_MINUTES = 10
