name: Install, Test, Lint, Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: 'Build and run the app'
      - uses: actions/checkout@v2
      - run: make env
        env:
          airtable_api_key: ${{ secrets.airtable_api_key }}
          airtable_database_id: ${{ secrets.airtable_database_id }}
          discord_guild_id: ${{ secrets.discord_guild_id }}
          discord_secret_token: ${{ secrets.discord_secret_token }}
          discord_review_channel_id: ${{ secrets.discord_review_channel_id }}
      - run: make setup
      - run: make build
      - run: make discord_bot
