name: Install, Test, Lint, Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    timeout-minutes: 3

    env:
      airtable_api_key: ${{ secrets.airtable_api_key }}
      airtable_database_id: ${{ secrets.airtable_database_id }}
      discord_guild_id: ${{ secrets.discord_guild_id }}
      discord_secret_token: ${{ secrets.discord_secret_token }}
      discord_review_channel_id: ${{ secrets.discord_review_channel_id }}

    steps:
      - uses: actions/checkout@v3
      - run: make env
      - run: make setup_for_deployment
      - run: make build
      - run: make discord_bot
