name: Install, Test, Lint, Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      airtable_api_key: ${{ secrets.airtable_api_key }}
      airtable_database_id: ${{ secrets.airtable_database_id }}
      discord_guild_id: ${{ secrets.discord_guild_id }}
      discord_secret_token: ${{ secrets.discord_secret_token }}
      discord_review_channel_id: ${{ secrets.discord_review_channel_id }}

    steps:
      - uses: actions/checkout@v3
      - run: make env
      - run: make build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 4
    if: github.ref == 'refs/heads/main'
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name deploy-discord-bot \
            --deployment-group-name discord-bot \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

